# export VLMEVALKIT_USE_MODELSCOPE=1 PIXELPRUNE_PATCH_IMPL=postvit PIXELPRUNE_SELECT_STAGE=post_vit_merged PIXELPRUNE_THRESHOLD=0.5 PIXELPRUNE_ANCHORED=false \
#   bash scripts/eval_doc_qwen35.sh "InfoVQA_VAL"

PIXELPRUNE_PATCH_IMPL=postvit PIXELPRUNE_SELECT_STAGE=post_vit_merged PIXELPRUNE_THRESHOLD=1 PIXELPRUNE_ANCHORED=false \
  bash scripts/eval_doc_qwen35.sh "InfoVQA_VAL"

PIXELPRUNE_PATCH_IMPL=postvit PIXELPRUNE_SELECT_STAGE=post_vit_merged PIXELPRUNE_THRESHOLD=1.5 PIXELPRUNE_ANCHORED=false \
  bash scripts/eval_doc_qwen35.sh "InfoVQA_VAL"

PIXELPRUNE_PATCH_IMPL=postvit PIXELPRUNE_SELECT_STAGE=post_vit_merged PIXELPRUNE_THRESHOLD=2 PIXELPRUNE_ANCHORED=false \
  bash scripts/eval_doc_qwen35.sh "InfoVQA_VAL"